import type { Metadata } from 'next';
import { Providers } from './providers';
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: 'Next.js 13.4 Presentation',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <NextTopLoader color='#e92a67' />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
